import { Link, useParams } from 'react-router-dom'
import { LoadingState } from '../../shared/components/LoadingState'
import { formatRedBoothDateTime, formatRedBoothTime } from '../../shared/utils/businessDate'
import { useAdminDailyOperationDetail } from '../hooks/useAdminDailyOperations'
import { formatAdminEtb } from '../utils/format'

export function AdminDailyOperationDetailPage() {
  const { businessDayId } = useParams()
  const { detail, loading, error } = useAdminDailyOperationDetail(businessDayId)
  if (loading) return <LoadingState label="Loading daily operation" />
  if (error || !detail) return <div className="rounded-2xl border bg-white p-10 text-center"><p className="font-semibold text-red-700">Unable to load daily operation.</p></div>

  const { businessDay: day, totals } = detail
  const actualOrExpected = day.actualRemainingPaper ?? totals.expectedRemaining
  const paperRight = totals.prints + totals.faultyPaper + actualOrExpected
  const paperBalanced = day.status === 'OPEN' || (day.paperDifference ?? 0) === 0
  const revenueBalanced = day.status === 'OPEN' || (day.revenueDifference ?? 0) === 0
  const serious = day.status === 'CLOSED_WITH_DISCREPANCY' || (day.paperDifference ?? 0) !== 0 || (day.revenueDifference ?? 0) !== 0

  return <div className="mx-auto max-w-7xl space-y-6">
    <header className="border-b pb-6"><Link to={`/admin/daily-operations?date=${day.businessDate}`} className="text-sm font-semibold text-redbooth-600">← Daily Operations</Link><div className="mt-5 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-redbooth-600">{detail.booth.locationName}</p><h1 className="mt-2 text-3xl font-bold">{detail.booth.name}</h1><p className="mt-2 text-sm text-gray-500">{day.businessDate} · {detail.salespersonName}</p></div><StatusBadge status={day.status} /></div></header>

    {(serious || totals.missingProofs > 0 || day.status === 'PENDING_REVIEW') && <section className="flex flex-wrap gap-3">{(day.paperDifference ?? 0) !== 0 && <Alert text={`Paper Difference: ${day.paperDifference}`} serious />}{(day.revenueDifference ?? 0) !== 0 && <Alert text={`Revenue Difference: ${formatAdminEtb(day.revenueDifference ?? 0)}`} serious />}{totals.missingProofs > 0 && <Alert text={`Missing Proofs: ${totals.missingProofs}`} />}{day.status === 'PENDING_REVIEW' && <Alert text="Pending Review" />}</section>}

    <Section title="General Summary"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Info label="Salesperson" value={detail.salespersonName} /><Info label="Business Date" value={day.businessDate} /><Info label="Started At" value={formatRedBoothDateTime(day.startedAt)} /><Info label="Closed At" value={day.closedAt ? formatRedBoothDateTime(day.closedAt) : 'Not completed'} /><Info label="Transactions" value={totals.transactions} /><Info label="Prints Sold" value={totals.prints} /><Info label="Revenue" value={formatAdminEtb(totals.revenue)} /></div></Section>

    <Section title="Paper Control"><div className="grid gap-5 lg:grid-cols-[1fr_auto_1fr]"><div className="grid grid-cols-3 gap-3"><Info label="Starting" value={day.startingPaper} /><Info label="Added" value={totals.addedPaper} /><Info label="Available" value={day.startingPaper + totals.addedPaper} /></div><div className="self-center text-center text-2xl font-light text-gray-300">=</div><div className="grid grid-cols-3 gap-3"><Info label="Sold" value={totals.prints} /><Info label="Faulty" value={totals.faultyPaper} /><Info label={day.status === 'OPEN' ? 'Expected' : 'Remaining'} value={actualOrExpected} /></div></div><div className={`mt-5 rounded-xl p-4 text-sm font-semibold ${paperBalanced ? 'bg-green-50 text-green-800' : 'bg-red-50 text-red-800'}`}>{day.startingPaper} + {totals.addedPaper} = {totals.prints} + {totals.faultyPaper} + {actualOrExpected} <span className="ml-3">{day.status === 'OPEN' ? `Expected remaining: ${totals.expectedRemaining}` : paperBalanced ? 'Balanced' : `Difference: ${day.paperDifference}`}</span><span className="sr-only">Right side total {paperRight}</span></div>
      <div className="mt-6 grid gap-6 lg:grid-cols-2"><RecordList title="Paper Movement History" records={detail.paperRecords} empty="No paper movements recorded." /><RecordList title="Faulty Paper" records={detail.faultyRecords} empty="No faulty paper recorded." /></div>
    </Section>

    <div className="grid gap-6 xl:grid-cols-2"><Section title="Sales & Revenue"><div className="grid grid-cols-3 gap-3"><Info label="Transactions" value={totals.transactions} /><Info label="Prints Sold" value={totals.prints} /><Info label="Gross Revenue" value={formatAdminEtb(totals.revenue)} /></div><h3 className="mt-6 text-sm font-bold">Payment Breakdown</h3><dl className="mt-3 space-y-2">{totals.paymentTotals.length ? totals.paymentTotals.map((payment) => <div key={payment.code} className="flex justify-between text-sm"><dt>{payment.code}</dt><dd className="font-semibold">{formatAdminEtb(payment.amount)}</dd></div>) : <p className="text-sm text-gray-500">No completed sales.</p>}<div className="flex justify-between border-t pt-3 font-bold"><dt>Total</dt><dd>{formatAdminEtb(totals.revenue)}</dd></div></dl><Link to={`/admin/transactions?businessDay=${day.id}&date=${day.businessDate}`} className="mt-5 inline-flex min-h-10 items-center rounded-lg border px-3 text-sm font-semibold">View Transactions</Link></Section>
      <Section title="Reconciliation"><div className="space-y-5"><ReconciliationBlock title="PAPER" rows={[['Expected Remaining', totals.expectedRemaining], ['Actual Remaining', day.actualRemainingPaper ?? 'Not yet entered'], ['Difference', day.paperDifference ?? 'Not closed'], ['Status', day.status === 'OPEN' ? 'In progress' : paperBalanced ? 'Balanced' : 'Discrepancy']]} /><ReconciliationBlock title="REVENUE" rows={[['Expected Revenue', formatAdminEtb(day.expectedRevenue ?? totals.revenue)], ['Recorded Revenue', day.recordedRevenue === null ? 'Not closed' : formatAdminEtb(day.recordedRevenue)], ['Difference', day.revenueDifference === null ? 'Not closed' : formatAdminEtb(day.revenueDifference)], ['Status', day.status === 'OPEN' ? 'In progress' : revenueBalanced ? 'Balanced' : 'Discrepancy']]} /><ReconciliationBlock title="VERIFICATION" rows={[['Digital Transactions', totals.digitalTransactions], ['Verified Proofs', totals.verifiedProofs], ['Missing Proofs', totals.missingProofs]]} /><div className={`rounded-xl p-4 text-center font-bold ${serious ? 'bg-red-50 text-red-800' : day.status === 'PENDING_REVIEW' ? 'bg-orange-50 text-orange-800' : 'bg-green-50 text-green-800'}`}>{day.status === 'OPEN' ? 'OPEN' : day.status.replaceAll('_', ' ')}</div></div></Section></div>

    <div className="grid gap-6 xl:grid-cols-2"><Section title="Closing Information">{day.status === 'OPEN' ? <p className="rounded-xl bg-green-50 p-4 text-sm font-semibold text-green-800">Business day is currently open.</p> : <div className="grid grid-cols-2 gap-4"><Info label="Closed At" value={day.closedAt ? formatRedBoothDateTime(day.closedAt) : 'Not recorded'} /><Info label="Actual Remaining" value={day.actualRemainingPaper ?? 'Not recorded'} /><Info label="Closing Status" value={day.closingStatus ?? day.status} /><Info label="Closing Notes" value={day.closingNotes ?? 'No notes'} /></div>}</Section>
      <Section title="Operation Timeline"><ol className="space-y-4">{detail.timeline.map((event) => <li key={event.id} className="flex gap-4"><time className="w-20 shrink-0 text-xs font-semibold text-gray-500">{formatRedBoothTime(event.occurredAt)}</time><div className="border-l-2 border-gray-200 pl-4"><p className="text-sm font-semibold">{event.label}</p><p className="mt-1 text-xs text-gray-500">{event.detail}</p></div></li>)}</ol></Section></div>
  </div>
}

function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="font-bold">{title}</h2><div className="mt-5">{children}</div></section> }
function Info({ label, value }: { label: string; value: string | number }) { return <div><p className="text-xs text-gray-500">{label}</p><p className="mt-1 font-semibold tabular-nums">{value}</p></div> }
function Alert({ text, serious }: { text: string; serious?: boolean }) { return <div className={`rounded-xl border px-4 py-2 text-sm font-semibold ${serious ? 'border-red-200 bg-red-50 text-red-800' : 'border-orange-200 bg-orange-50 text-orange-800'}`}>{text}</div> }
function StatusBadge({ status }: { status: string }) { const serious = status === 'CLOSED_WITH_DISCREPANCY'; return <span className={`w-fit rounded-full px-3 py-1.5 text-sm font-bold ${serious ? 'bg-red-50 text-red-800' : status === 'PENDING_REVIEW' ? 'bg-orange-50 text-orange-800' : 'bg-green-50 text-green-800'}`}>{status.replaceAll('_', ' ')}</span> }
function ReconciliationBlock({ title, rows }: { title: string; rows: Array<[string, string | number]> }) { return <div><h3 className="text-xs font-bold tracking-widest text-gray-400">{title}</h3><dl className="mt-2 space-y-2">{rows.map(([label, value]) => <div key={label} className="flex justify-between gap-4 text-sm"><dt className="text-gray-500">{label}</dt><dd className="font-semibold">{value}</dd></div>)}</dl></div> }
function RecordList({ title, records, empty }: { title: string; records: Array<{ id: string; kind: string; quantity: number; reason?: string; notes?: string | null; actorName: string; createdAt: string; proofUrl: string | null }>; empty: string }) { return <div><h3 className="text-sm font-bold">{title}</h3>{records.length ? <div className="mt-3 divide-y rounded-xl border">{records.map((record) => <div key={record.id} className="p-3 text-sm"><div className="flex justify-between gap-3"><div><p className="font-semibold">{record.kind.replaceAll('_', ' ')} · {record.quantity}</p>{record.reason && <p className="mt-1 text-gray-600">{record.reason}</p>}{record.notes && <p className="mt-1 text-gray-500">{record.notes}</p>}<p className="mt-1 text-xs text-gray-400">{record.actorName} · {formatRedBoothDateTime(record.createdAt)}</p></div>{record.proofUrl ? <a href={record.proofUrl} target="_blank" rel="noreferrer" className="h-fit rounded-lg border px-2 py-1 text-xs font-semibold">View proof</a> : <span className="text-xs text-gray-400">No proof</span>}</div></div>)}</div> : <p className="mt-3 text-sm text-gray-500">{empty}</p>}</div> }
