import { useEffect, useMemo, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { LoadingState } from '../../shared/components/LoadingState'
import { Attention, BoothTable, Drilldowns, HealthSections, MoneySections, ReportFilters, ReportHeader, SummaryCards, TrendChart, TrendTable } from '../components/ReportComponents'
import { useWeeklyReport } from '../hooks/useWeeklyReport'
import { compareReports, getAdminReport, getReportOptions } from '../services/adminReportsService'
import type { Comparison, ReportOptions } from '../types/reports'
import { addReportDays, endOfReportWeek, formatReportDate, startOfReportWeek } from '../utils/reportDates'

const empty:ReportOptions={locations:[],booths:[]}
export function AdminWeeklyReportsPage(){const [params,setParams]=useSearchParams();const [start,setStart]=useState(startOfReportWeek(params.get('weekStart')??undefined));const [locationId,setLocation]=useState(params.get('location')??'');const [boothId,setBooth]=useState(params.get('booth')??'');const [options,setOptions]=useState(empty);const [comparison,setComparison]=useState<Comparison|null>(null);const end=endOfReportWeek(start);const filters=useMemo(()=>({dateFrom:start,dateTo:end,locationId,boothId}),[start,end,locationId,boothId]);const {report,loading,error}=useWeeklyReport(filters);useEffect(()=>{void getReportOptions().then(setOptions)},[]);useEffect(()=>{const next:Record<string,string>={weekStart:start};if(locationId)next.location=locationId;if(boothId)next.booth=boothId;setParams(next,{replace:true})},[start,locationId,boothId,setParams]);useEffect(()=>{if(!report)return;let active=true;const previous={...filters,dateFrom:addReportDays(start,-7),dateTo:addReportDays(end,-7)};void getAdminReport(previous).then(p=>{if(active)setComparison(compareReports(report,p))});return()=>{active=false}},[report,filters,start,end]);const period=`${formatReportDate(start,{month:'short',day:'numeric'})} – ${formatReportDate(end)}`;return <div className="mx-auto max-w-[1500px]"><ReportHeader title="Weekly Report" subtitle="Review RedBooth performance across the selected business week." period={period}><button onClick={()=>setStart(addReportDays(start,-7))} className="rounded-xl border bg-white px-4 font-semibold">Previous Week</button><button onClick={()=>setStart(addReportDays(start,7))} className="rounded-xl border bg-white px-4 font-semibold">Next Week</button></ReportHeader><ReportFilters options={options} locationId={locationId} boothId={boothId} onLocation={setLocation} onBooth={setBooth}><label className="min-w-48 flex-1 text-xs font-semibold">Week Starting Monday<input type="date" value={start} onChange={e=>setStart(startOfReportWeek(e.target.value))} className="mt-1 min-h-10 w-full rounded-lg border bg-white px-3 text-sm"/></label></ReportFilters>{loading?<LoadingState label="Loading weekly report"/>:error||!report?<p className="mt-6 rounded-2xl border bg-white p-10 text-center font-semibold text-red-700">Unable to load report.</p>:<><SummaryCards report={report} comparison={comparison}/><TrendChart rows={report.trend}/><TrendTable rows={report.trend}/><MoneySections report={report}/><HealthSections report={report}/><BoothTable report={report}/><Attention report={report}/><Drilldowns {...filters}/></>}</div>}
