import { useEffect, useMemo, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { LoadingState } from '../../shared/components/LoadingState'
import { Attention, BoothTable, Drilldowns, HealthSections, MoneySections, ReportFilters, ReportHeader, SummaryCards, TrendChart, WeeklyRollup } from '../components/ReportComponents'
import { useMonthlyReport } from '../hooks/useMonthlyReport'
import { compareReports, getAdminReport, getReportOptions } from '../services/adminReportsService'
import type { Comparison, ReportOptions } from '../types/reports'
import { formatReportDate, monthRange, previousMonthRange } from '../utils/reportDates'

const empty:ReportOptions={locations:[],booths:[]}
export function AdminMonthlyReportsPage(){const [params,setParams]=useSearchParams();const initial=params.get('month')??new Date().toLocaleDateString('en-CA',{timeZone:'Africa/Addis_Ababa',year:'numeric',month:'2-digit'});const [month,setMonth]=useState(initial);const [locationId,setLocation]=useState(params.get('location')??'');const [boothId,setBooth]=useState(params.get('booth')??'');const [options,setOptions]=useState(empty);const [comparison,setComparison]=useState<Comparison|null>(null);const range=monthRange(`${month}-01`);const filters=useMemo(()=>({dateFrom:range.from,dateTo:range.to,locationId,boothId}),[range.from,range.to,locationId,boothId]);const {report,loading,error}=useMonthlyReport(filters);useEffect(()=>{void getReportOptions().then(setOptions)},[]);useEffect(()=>{const next:Record<string,string>={month};if(locationId)next.location=locationId;if(boothId)next.booth=boothId;setParams(next,{replace:true})},[month,locationId,boothId,setParams]);useEffect(()=>{if(!report)return;let active=true;const prior=previousMonthRange(`${month}-01`);void getAdminReport({...filters,dateFrom:prior.from,dateTo:prior.to}).then(p=>{if(active)setComparison(compareReports(report,p))});return()=>{active=false}},[report,filters,month]);const period=formatReportDate(range.from,{month:'long',year:'numeric'});return <div className="mx-auto max-w-[1500px]"><ReportHeader title="Monthly Report" subtitle="High-level RedBooth business performance for the selected month." period={period}/><ReportFilters options={options} locationId={locationId} boothId={boothId} onLocation={setLocation} onBooth={setBooth}><label className="min-w-48 flex-1 text-xs font-semibold">Month<input type="month" value={month} onChange={e=>setMonth(e.target.value)} className="mt-1 min-h-10 w-full rounded-lg border bg-white px-3 text-sm"/></label></ReportFilters>{loading?<LoadingState label="Loading monthly report"/>:error||!report?<p className="mt-6 rounded-2xl border bg-white p-10 text-center font-semibold text-red-700">Unable to load report.</p>:<><SummaryCards report={report} comparison={comparison}/><TrendChart rows={report.trend}/><MoneySections report={report}/><HealthSections report={report}/><BoothTable report={report}/><WeeklyRollup rows={report.trend}/><Attention report={report}/><Drilldowns {...filters}/></>}</div>}
