import type { PostgrestError } from '@supabase/supabase-js'
import { getSupabaseClient } from '../../lib/supabase/client'
import type { BoothFilters, BoothHistory, BoothOptions, BoothRecord, BoothStatus, BoothSummary } from '../types/booths'

export const BOOTHS_PAGE_SIZE=25
const supabase=()=>getSupabaseClient()
function friendly(error:PostgrestError|null,fallback:string){if(error?.code==='42501')return'You do not have permission to manage booths.';if(error?.code==='23505')return'A booth with this code or name already exists.';if(error?.message.includes('open business day'))return'A booth with an open business day cannot be deactivated.';return fallback}
export async function getBoothOptions():Promise<BoothOptions>{const {data,error}=await supabase().from('locations').select('id,name,status').order('name');if(error)throw new Error('Locations could not be loaded.');return{locations:(data??[]).map(r=>({id:String(r.id),name:String(r.name),status:String(r.status) as BoothStatus}))}}
export async function getBooths(filters:BoothFilters,page:number):Promise<{records:BoothRecord[];count:number;summary:BoothSummary}>{let query=supabase().from('admin_booth_details').select('*',{count:'exact'});if(filters.locationId)query=query.eq('location_id',filters.locationId);if(filters.status)query=query.eq('status',filters.status);if(filters.operationalState)query=query.eq('operational_state',filters.operationalState);if(filters.search.trim())query=query.or(`name.ilike.%${filters.search.trim()}%,code.ilike.%${filters.search.trim()}%`);query=query.order('name').range((page-1)*BOOTHS_PAGE_SIZE,page*BOOTHS_PAGE_SIZE-1);const [rows,total]=await Promise.all([query,supabase().rpc('admin_booth_summary')]);if(rows.error)throw new Error(friendly(rows.error,'Unable to load booths.'));if(total.error)throw new Error('Unable to load booth summary. Apply the latest Supabase migration.');const s=Array.isArray(total.data)?total.data[0]:total.data;return{records:(rows.data??[]) as BoothRecord[],count:rows.count??0,summary:{total:Number(s?.total_booths??0),active:Number(s?.active_booths??0),operating:Number(s?.operating_today??0),attention:Number(s?.needs_attention??0)}}}
export async function createBooth(input:{name:string;code:string;locationId:string;status:BoothStatus}){const {error}=await supabase().from('booths').insert({name:input.name.trim(),code:input.code.trim().toUpperCase(),location_id:input.locationId,status:input.status});if(error)throw new Error(friendly(error,'The booth could not be created.'))}
export async function updateBooth(input:{id:string;name:string;locationId:string;status:BoothStatus}){const {error}=await supabase().rpc('admin_update_booth',{p_booth_id:input.id,p_name:input.name,p_location_id:input.locationId,p_status:input.status});if(error)throw new Error(friendly(error,error.message.includes('open business day')?'A booth with an open business day cannot be deactivated.':'The booth could not be updated.'))}
export async function getBoothHistory(id:string):Promise<BoothHistory[]>{const {data,error}=await supabase().from('admin_booth_history').select('*').eq('booth_id',id).order('business_date',{ascending:false}).limit(10);if(error)throw new Error('Recent booth history could not be loaded.');return(data??[]) as BoothHistory[]}
export async function createLocation(name:string){const {error}=await supabase().from('locations').insert({name:name.trim()});if(error)throw new Error(error.code==='23505'?'A location with this name already exists.':'The location could not be created.')}
export async function updateLocation(input:{id:string;name:string;status:BoothStatus}){if(input.status==='INACTIVE'){const {count,error}=await supabase().from('booths').select('id',{count:'exact',head:true}).eq('location_id',input.id).eq('status','ACTIVE');if(error)throw new Error('The location could not be checked.');if(count)throw new Error('Deactivate or move active booths before deactivating this location.')}const {error}=await supabase().from('locations').update({name:input.name.trim(),status:input.status}).eq('id',input.id);if(error)throw new Error(error.code==='23505'?'A location with this name already exists.':'The location could not be updated.')}
