import type{PostgrestError}from'@supabase/supabase-js'
import{getSupabaseClient}from'../../lib/supabase/client'
import type{SalespersonFilters,SalespersonHistory,SalespersonOptions,SalespersonRecord,SalespersonStatus,SalespersonSummary}from'../types/salespersons'
export const SALESPERSONS_PAGE_SIZE=25;const supabase=()=>getSupabaseClient()
function friendly(error:PostgrestError|null,fallback:string){const m=error?.message.toLowerCase()??'';if(error?.code==='42501')return'You do not have permission to manage salespersons.';if(m.includes('open business day'))return'This salesperson has an open business day.';if(m.includes('already assigned'))return'This salesperson is already assigned.';return fallback}
export async function getSalespersonOptions():Promise<SalespersonOptions>{const[locations,booths]=await Promise.all([supabase().from('locations').select('id,name').eq('status','ACTIVE').order('name'),supabase().from('booths').select('id,name,location_id').eq('status','ACTIVE').order('name')]);if(locations.error||booths.error)throw new Error('Assignment options could not be loaded.');return{locations:(locations.data??[]).map(r=>({id:String(r.id),name:String(r.name)})),booths:(booths.data??[]).map(r=>({id:String(r.id),name:String(r.name),locationId:String(r.location_id)}))}}
export async function getSalespersons(filters:SalespersonFilters,page:number):Promise<{records:SalespersonRecord[];count:number;summary:SalespersonSummary}>{let q=supabase().from('admin_salesperson_details').select('*',{count:'exact'});if(filters.status)q=q.eq('status',filters.status);if(filters.locationId)q=q.eq('location_id',filters.locationId);if(filters.boothId)q=q.eq('booth_id',filters.boothId);if(filters.assignmentState==='ASSIGNED')q=q.not('assignment_id','is',null);if(filters.assignmentState==='UNASSIGNED')q=q.is('assignment_id',null);if(filters.search.trim())q=q.or(`full_name.ilike.%${filters.search.trim()}%,email_snapshot.ilike.%${filters.search.trim()}%`);const sort=filters.sort==='NAME_DESC'?['full_name',false]as const:filters.sort==='REVENUE_DESC'?['today_revenue',false]as const:filters.sort==='RECENT_ACTIVITY'?['latest_activity',false]as const:['full_name',true]as const;q=q.order(sort[0],{ascending:sort[1],nullsFirst:false}).range((page-1)*SALESPERSONS_PAGE_SIZE,page*SALESPERSONS_PAGE_SIZE-1);const[rows,total]=await Promise.all([q,supabase().rpc('admin_salesperson_summary')]);if(rows.error)throw new Error(friendly(rows.error,'Unable to load salespersons.'));if(total.error)throw new Error('Unable to load salesperson summary. Apply the latest Supabase migration.');const s=Array.isArray(total.data)?total.data[0]:total.data;return{records:(rows.data??[])as SalespersonRecord[],count:rows.count??0,summary:{total:Number(s?.total??0),active:Number(s?.active??0),assigned:Number(s?.assigned??0),unassigned:Number(s?.unassigned??0)}}}
export async function createSalesperson(input:{fullName:string;email:string;password:string;status:SalespersonStatus}){
  const client=supabase()
  const{data:sessionData,error:sessionError}=await client.auth.getSession()
  const session=sessionData.session
  const accessToken=session?.access_token
  if(sessionError||!session||!accessToken)throw new Error('Your Admin session is missing or expired. Sign in again.')
  const{data:verified,error:verifyError}=await client.auth.getUser(accessToken)
  if(verifyError||!verified.user)throw new Error('Your current Admin session could not be verified. Sign out and sign in again.')
  if(verified.user.id!==session.user.id)throw new Error('The stored Supabase session is inconsistent. Sign out and sign in again.')
  const{data,error}=await client.functions.invoke('create-salesperson',{body:input,headers:{Authorization:`Bearer ${accessToken}`}})
  if(error){let message='Unable to create salesperson. Confirm the Edge Function is deployed and configured.';const context='context'in error?error.context:null;if(context instanceof Response){try{const body=await context.clone().json()as{error?:unknown};if(typeof body.error==='string')message=body.error}catch{/* Keep the safe fallback. */}}throw new Error(message)}
  if(data?.error)throw new Error(String(data.error))
  return data.salesperson as{id:string;email:string;fullName:string;status:SalespersonStatus}
}
export async function updateSalesperson(input:{id:string;fullName:string;status:SalespersonStatus}){const{error}=await supabase().rpc('admin_update_salesperson',{p_salesperson_id:input.id,p_full_name:input.fullName,p_status:input.status});if(error)throw new Error(friendly(error,'Unable to update salesperson.'))}
export async function assignSalesperson(input:{salespersonId:string;boothId:string;startDate:string}){const{error}=await supabase().rpc('admin_assign_salesperson_to_booth',{p_salesperson_id:input.salespersonId,p_booth_id:input.boothId,p_start_date:input.startDate});if(error)throw new Error(friendly(error,'Unable to update assignment.'))}
export async function endSalespersonAssignment(input:{salespersonId:string;endDate:string}){const{error}=await supabase().rpc('admin_end_salesperson_assignment',{p_salesperson_id:input.salespersonId,p_end_date:input.endDate});if(error)throw new Error(friendly(error,'Unable to end assignment.'))}
export async function getSalespersonHistory(id:string):Promise<SalespersonHistory[]>{const{data,error}=await supabase().from('admin_salesperson_history').select('*').eq('salesperson_id',id).order('business_date',{ascending:false}).limit(10);if(error)throw new Error('Recent operational history could not be loaded.');return(data??[])as SalespersonHistory[]}
